@startuml

package "context map" {
    package "board context"{
        package "board"{
            entity Board <<Aggregate Root>>{
            }
        }

        package "post"{
            abstract Post <<Aggregate Root>>{
            }
            class GuestPost <<ImplClass>>{
            }
            class MemberPost <<ImplClass>>{
            }
            '해시태그
            entity HashTag <<Entity>>{
            }
            struct Tags <<Value Object>>{
            }
            Post -- Tags
            Tags "1" --> "N" HashTag
            '좋아요
            entity PostLike <<Entity>>{
            }
            struct Likes <<Value Object>>{
            }
            Post -- Likes
            Likes "1" --> "N" PostLike
        }

        package "comment"{
            abstract Comment <<Aggregate Root>>{
            }
            class GuestComment <<ImplClass>>{
            }
            class MemberComment <<ImplClass>>{
            }
        }

        package "userBoardRole"{
            abstract UserBoardRole <<Aggregate Root>>{
            }
        }

        GuestPost --|> Post
        MemberPost --|> Post
        GuestComment --|> Comment
        MemberComment --|> Comment

    }

    package "member context"{
        entity Member <<Aggregate Root>>{
        }
    }

    Board <.. userBoardRole
    Board <.. Post

    userBoardRole ..> Member
    MemberPost ..> Member
    PostLike ..> Member
    MemberComment ..> Member
    Comment ..> Post
    Comment --> Comment

}
@enduml
