@startuml PostDetailSeqWithCache
title Get post detailed
actor Client
participant PostQueryController
participant PostQueryService
participant PostQueryRepository
participant CommentQueryRepository #orange
participant "DomainEventPublisher\n(async)" as DomainEventPublisher #skyblue
participant ViewCountCacheHandler #skyblue
participant "PostWriteCacheRepository\n(write cache)" as PostCacheRepository
database    Cache

Client -> PostQueryController : GET /posts/{postId}?board={bname}
PostQueryController -> PostQueryService : getPostDetailed(Visitor, postId, bname)
PostQueryService -> PostQueryRepository : fetchDetailed(postId, bname)
PostQueryRepository --> PostQueryService : PostDetailDTO
PostQueryService -> CommentQueryRepository : fetchCommentList(postId, page)
CommentQueryRepository --> PostQueryService : CommentListDTO
alt Post exists & not deleted
    PostQueryService -> DomainEventPublisher : publish(PostViewIncreasedEvent(postId))
    PostQueryService --> PostQueryController : PostDetailResult
    PostQueryController --> Client : 200 OK + PostDetailResponse
    DomainEventPublisher --> ViewCountCacheHandler : PostViewIncreasedEvent
    ViewCountCacheHandler -> PostCacheRepository : increaseViewCount(postId)
    PostCacheRepository -> Cache : INCR post:{postId}:views
else Post not found
    PostQueryController --> Client : 404_POST_NOT_FOUND
else Post deleted
    PostQueryController --> Client : 410_POST_DELETED
end
@enduml


