@startuml
package "member" {
  entity Member <<Aggregate Root>> {
    +Long memberId
    +Nickname nickname
    +Gender gender
    +BirthYear birthYear
    +LocalDateTime signUpDate
    --
    +withdraw()
    +updateNickname(String)
}

enum Gender {
    MALE
    FEMALE
}

class Nickname <<Value Object>> {
    +String : nickname
    --
    +Nickname : static of(String, NicknamePolicy)
}

class NicknamePolicy <<Policy>> {
  + checkFormat()
  + checkDuplicate()
}
class BirthYear <<Value Object>> {
    +String : birthYear
    --
    +validate(String)
}

Member -- Gender
Member -- Nickname
Member -- BirthYear
Nickname -- NicknamePolicy
}
@enduml