@startuml
package "member" {
  entity Member <<Aggregate Root>> {
    +Long memberId
    +Nickname nickname
    +Gender gender
    +BirthYear birthYear
    +LocalDateTime signUpDate
    --
    +create()
    +withdraw()
    +updateNickname(String) : nickname.updateNickname(String)
}

enum Gender {
    MALE
    FEMALE
}

class Nickname <<Value Object>> {
    +String : nickname
    --
    +validate()
    +updateNickname(newNickname : String) : Nickname
}

class BirthYear <<Value Object>> {
    +String : birthYear
    --
    +validate()
}

Member -- Gender
Member -- Nickname
Member -- BirthYear
}
@enduml