@startuml createPostSeq
title createPost
actor Client
participant PostController
participant PostQueryService
participant BoardQueryRepository #yellow
participant PostCommandRepository
entity      Post
participant DomainEventPublisher #skyblue

Client -> PostController : POST /posts\n(bname, page, size)
PostController -> PostQueryService : createPost(userId, cmd)

PostQueryService -> BoardQueryRepository : findIdByBoardName(bname)
BoardQueryRepository --> PostQueryService : boardId

PostQueryService -> Post : Post.write(cmd, boardId)
activate Post
Post --> PostQueryService : Post Created
deactivate Post

PostQueryService -> PostCommandRepository : save(Post)
PostCommandRepository --> PostQueryService : PostId

PostQueryService -> DomainEventPublisher : publish(PostCreatedEvent)

PostQueryService --> PostController : PostId
PostController --> Client :  201 Created + PostId
@enduml