@startuml getPostListSeq
actor Client
participant PostQueryController
participant PostQueryService
participant BoardQueryRepository #yellow
participant PostQueryRepository
participant PostMetaInfoRepository

title Get Post list

Client -> PostQueryController : GET /posts\n?board={bname}\n&page={page}&size={size}\n&searchType={type}&keyword={kw}

PostQueryController -> PostQueryService : getPostList(bname, Page, searchCond)

PostQueryService -> BoardQueryRepository : findIdByBoardName(bname)
alt Board exists
BoardQueryRepository --> PostQueryService : boardId

PostQueryService -> PostQueryRepository : findList(boardId, Page, searchCond)
PostQueryRepository -> PostMetaInfoRepository : fetchCommentCounts(postIds)
PostMetaInfoRepository --> PostQueryRepository : List<CommentCount>
PostQueryRepository --> PostQueryService : Slice<PostSummaryDTO>


PostQueryService --> PostQueryController : PostListResult
PostQueryController --> Client : 200 OK + PostListResponse
else Board not found
  BoardQueryRepository --> Client : 404_BOARD_NOT_FOUND
end

@enduml
