@startuml
package "UserBoardRole"{
    entity BoardManager <<Aggregate Root>>{
            +Post :\t\t post
            +Content :\t\t content
            +DateTime :\t createdAt
            +DateTime :\t updatedAt
            +Boolean :\t\t isDeleted
    }
    entity Role <<Entity>>{
    }
    struct Roles <<Value Object>>{
    }
    struct Members <<Value Object>>{
    }
}

BoardManager -- Roles
BoardManager -- Members
Roles "1" --> "N" Role
@enduml