@startuml
actor User
participant MemberController
participant MemberQueryService
participant MemberQueryRepository
entity Member
participant MemberProfileMapper


User -> MemberController : GET /users/me
MemberController -> MemberQueryService : getProfileById(memberId)

MemberQueryService -> MemberQueryRepository : findById(memberId)
MemberQueryRepository --> MemberQueryService : Member

MemberQueryService -> Member : toProfileResult()
Member --> MemberQueryService : MemberProfileResult

MemberQueryService -> MemberProfileMapper : toResponse(MemberProfileResult)
MemberProfileMapper --> MemberQueryService : MemberProfileResponse

MemberQueryService --> MemberController : MemberProfileResponse
MemberController --> User : HTTP 200 OK + JSON 응답
@enduml