@startuml
actor Client
participant BoardController
participant BoardService
participant BoardCommandRepository
Entity Board

Client -> BoardController : POST /board \n(boardCreateRequest)

BoardController -> BoardService : createBoard \n(boardCreateRequest, userId)

BoardService -> Board : Board.create(boardCreateRequest)

activate Board
Board --> BoardService : Board created
deactivate Board

BoardService -> BoardCommandRepository : save(board)
BoardCommandRepository --> BoardService : BoardId

BoardService -> DomainEventPublisher : publish(BoardCreatedEvent)

BoardService --> BoardController : BoardId
BoardController --> Client : HTTP 201 + BoardId
@enduml