@startuml
package "board" {
    entity Board <<Aggregate Root>> {
        +Long boardId
        +BoardName boardName
        +CreatorId memberId
        +createdAt dateTime
        --
        +create(boardName : String, creatorId : MemberId) : Board
        +delete()
        +validateBoardName() : BoardName.validate()
    }
    'VO
    class BoardName <<Value Object>> {
        +String : boardName
        --
        +validate()
     }
}
@enduml
