@startuml
package "permissionPolicy" {
  class PermissionPolicy <<Aggregate Root>>{
    - Long boardId
    - List<ManagerAssignment> managerAssignments
    + boolean can(Long userId, Permission permission)
    + assignManager(Long userId, Role role)
    + delegate(Long from, UserId to, RoleType roleType)
  }

  entity ManagerAssignment <<Entity>>{
    - Long managerAssignmentId
    - Long userId
    - Role role
    + boolean isSameUser(Long userId)
    + boolean hasPermission(Permission permission)
  }

  struct Role <<Value Object>>{
    - RoleType roleType
    - Set<Permission> permissions
    + boolean hasPermission(Permission permission)
  }

  enum RoleType {
    SUPER_ADMIN
    COMMENT_ADMIN
    POST_ADMIN
  }

  enum Permission {
    DELETE_BOARD
    CREATE_BOARD
  }

  PermissionPolicy "1" o-- "*" ManagerAssignment
  ManagerAssignment "*" --> "1" Role
  Role --> RoleType
  Role --> Permission
}
@enduml