@startuml
package "userBoardRole" {
    entity UserBoardRole <<Aggregate Root>> {
        +Member : \t\t member
        +Board : \t\t board \t//외부 BC 키
        +Role : \t\t role
        +DateTime : \t assignedAt
        --
        +createManager(board : Board, creatorId : MemberId) : UserBoardRole
        +grantRole(to : MemberId, role : Role)
        +transferRole(to : MemberId)
        +revokeRole()
        +assertRole(targetRole : Role)
        +assertOwner(memberId : MemberId)
        +assertBelongsTo(board : Board)
    }

    enum Role {
        MANAGER
        EDITOR
    }

    'VO
    class Member <<Value Object>> {
        +Long : memberId
    }

    class Board <<Value Object>> {
        +Long : boardId
    }


    UserBoardRole -- Role
    UserBoardRole -- Board
    UserBoardRole -- Member
}
@enduml
