name: request pr review

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * 1-5'   # 평일 오전 10시마다 수행
    - cron: '0 10 * * 1-5'  # 평일 오후 7시
    - cron: '0 5 * * 0,6'   # 주말 오후 2시

jobs:
  cron:
    runs-on: [ubuntu-latest]
    steps:
      - name: Request PR Review
        uses: SnoopyComp/remind-pr-review@v1.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          slackIds: ${{ vars.SLACK_IDS }}
          slackBotToken: ${{ secrets.SLACK_BOT_TOKEN }}
          repoUrl: 'https://github.com/SimpleBoardTeam/simpleBoard-server'